import test from 'node:test';
import assert from 'node:assert/strict';
import {TimelineModel,validateData,DataValidationError,aggregateEvents,zoomRange,normalizeRange} from '../dist/core.js';

function fixture(){return {schemaVersion:1,lanes:[{id:'a',label:'Resource A'},{id:'b',label:'Resource B'},{id:'c',label:'Resource C'}],eventGroups:[{id:'g1',label:'Package 1'},{id:'g2',label:'Package 2'}],events:[
 {id:'e1',label:'Initiating event',time:100,laneIds:['a'],groupIds:['g1']},
 {id:'e2',label:'Move item',time:200,laneIds:['a','b'],groupIds:['g1'],transfers:[{from:'a',to:'b',itemId:'item'}]},
 {id:'e3',label:'Follow-on',time:300,laneIds:['b','c'],groupIds:['g2']},
 {id:'long',label:'Long interval',time:0,endTime:1000,laneIds:['c']},
 {id:'unrelated',label:'Coincidence',time:201,laneIds:['a']}
 ],relationships:[{id:'r1',source:'e1',target:'e2',kind:'causes'},{id:'r2',source:'e2',target:'e3',kind:'enables'},{id:'r3',source:'e2',target:'unrelated',kind:'correlates'}]};}

test('validates and defensively copies JSON input',()=>{const data=fixture(),model=new TimelineModel(data);data.events[0].label='mutated';assert.equal(model.events.get('e1').label,'Initiating event');});
test('rejects duplicate identities and invalid participant references',()=>{const d=fixture();d.events[1].id='e1';d.events[1].transfers[0].to='missing';assert.throws(()=>validateData(d),e=>e instanceof DataValidationError&&e.issues.some(x=>x.includes('duplicate'))&&e.issues.some(x=>x.includes('endpoints')));});
test('rejects naive strings, NaN, reversed intervals, and Date instances',()=>{for(const value of ['2026-01-01',NaN,new Date(),null,1.1]){const d=fixture();d.events[0].time=value;assert.throws(()=>validateData(d),DataValidationError);}const d=fixture();d.events[0].endTime=0;assert.throws(()=>validateData(d),DataValidationError);});
test('rejects dangling relationships and event groups',()=>{const d=fixture();d.relationships[0].target='unknown';d.events[0].groupIds=['no'];assert.throws(()=>validateData(d),DataValidationError);});
test('rejects non-JSON and cyclic metadata',()=>{for(const metadata of [{a:undefined},{a:Infinity},{a:1n}]){const d=fixture();d.events[0].metadata=metadata;assert.throws(()=>validateData(d),DataValidationError);}const d=fixture();d.events[0].metadata=d;assert.throws(()=>validateData(d),DataValidationError);});
test('interval query includes events spanning both viewport boundaries',()=>{const m=new TimelineModel(fixture());assert.deepEqual(m.query({start:210,end:290}).map(x=>x.id),['long']);});
test('filters combine lane, group, kind and text criteria',()=>{const m=new TimelineModel(fixture());assert.deepEqual(m.query({start:0,end:500},{laneIds:['b'],groupIds:['g1'],query:'item'}).map(x=>x.id),['e2']);assert.deepEqual(m.query({start:0,end:500},{laneIds:[]}),[]);});
test('causal trace follows declared directed edges, not neighboring timestamps',()=>{const m=new TimelineModel(fixture()),t=m.trace(['e2']);assert.deepEqual(t.upstream,['e1']);assert.deepEqual(t.downstream,['e3']);assert.deepEqual(new Set(t.relationshipIds),new Set(['r1','r2']));});
test('trace direction and depth are bounded, cycles terminate and roots remain distinct',()=>{const d=fixture();d.relationships.push({id:'r4',source:'e3',target:'e1',kind:'causes'});const m=new TimelineModel(d);assert.deepEqual(m.trace(['e1'],{direction:'downstream',maxDepth:1}).downstream,['e2']);const t=m.trace(['e1']);assert.equal(t.downstream.includes('e1'),false);assert.equal(new Set(t.downstream).size,2);assert.deepEqual(m.trace(['e1'],{maxDepth:0}).relationshipIds,[]);});
test('group expansion is direct, deduplicated, and does not snowball across overlaps',()=>{const d=fixture();d.events[1].groupIds=['g1','g2'];const m=new TimelineModel(d);assert.deepEqual(m.expandGroups(['e1']),['e1','e2']);assert.deepEqual(new Set(m.expandGroups(['e2'])),new Set(['e1','e2','e3']));});
test('aggregate cells count a multi-party event once per lane and retain member IDs',()=>{const d=fixture(),cells=aggregateEvents(d.events,{start:100,end:400},3);const b=cells.find(x=>x.laneId==='b'&&x.bucket===1);assert.deepEqual(b.eventIds,['e2']);assert.equal(cells.filter(x=>x.laneId==='c'&&x.eventIds.includes('long')).length,3);});
test('zoom preserves the pointer anchor and clamps extreme ranges',()=>{const range={start:100,end:1100},next=zoomRange(range,.5,.25);assert.equal(range.start+1000*.25,next.start+(next.end-next.start)*.25);assert.ok(zoomRange(range,1e-12).end-zoomRange(range,1e-12).start>=1);assert.throws(()=>zoomRange(range,0),RangeError);assert.throws(()=>normalizeRange({start:5,end:2}),RangeError);});
test('interval index agrees with a brute-force oracle on seeded random intervals',()=>{let seed=91;const rand=()=>((seed=(seed*1664525+1013904223)>>>0)/2**32);const d={schemaVersion:1,lanes:[{id:'a',label:'A'}],events:Array.from({length:2000},(_,i)=>{const time=Math.floor(rand()*10000);return {id:String(i),label:String(i),time,endTime:time+Math.floor(rand()*1500),laneIds:['a']};})};const m=new TimelineModel(d);for(let i=0;i<80;i++){const start=Math.floor(rand()*10000),end=start+500;assert.deepEqual(new Set(m.query({start,end}).map(x=>x.id)),new Set(d.events.filter(e=>e.time<=end&&e.endTime>=start).map(x=>x.id)));}});
test('core imports without a DOM',()=>{assert.equal(typeof globalThis.document,'undefined');assert.equal(new TimelineModel({schemaVersion:1,lanes:[],events:[]}).bounds().end,3600000);});
